// Generated by CoffeeScript 1.8.0
(function() {
  var fs, process;

  fs = require('fs');

  process = require('child_process');

  module.exports = function(photo, callback) {
    var err, killed, stderr, stdout, zbarimg;
    stdout = '';
    stderr = '';
    killed = false;
    if ((photo == null) || (callback == null) || photo.length === 0) {
      err = new Error('Missing parameter');
      callback(err, null);
      return false;
    }
    zbarimg = process.spawn('zbarimg', [photo, '-q']);
    zbarimg.stdout.setEncoding('utf8');
    zbarimg.stderr.setEncoding('utf8');
    zbarimg.stdout.on('data', function(data) {
      return stdout += data;
    });
    zbarimg.stderr.on('data', function(data) {
      return stderr += data;
    });
    zbarimg.on('error', function(err) {
      if (killed === true) {
        return false;
      }
      killed = true;
      callback(err, null);
      return true;
    });
    return zbarimg.on('close', function(code) {
      if (killed === true) {
        return false;
      }
      killed = true;
      if (stdout != null) {
        if (stdout.indexOf('QR-Code:') !== -1) {
          stdout = stdout.replace('QR-Code:', '');
          stdout = stdout.slice(0, -1);
          callback(null, stdout);
          return true;
        } else {
          err = new Error('No QR-Code found or barcode not supported');
          callback(err, null);
          return false;
        }
      }
      if (stderr != null) {
        err = new Error(stderr);
        callback(err, null);
        return false;
      }
    });
  };

}).call(this);
