// Generated by CoffeeScript 1.7.1
(function() {
  var escapeshell, fs, process;

  fs = require('fs');

  process = require('child_process');

  escapeshell = function(cmd) {
    return '"' + cmd.replace(/(["'$`\\])/g, '\\$1') + '"';
  };

  module.exports = function(photo, callback) {
    var err, zbarimg;
    if ((photo == null) || (callback == null) || photo.length === 0) {
      err = new Error('Missing parameter');
      callback(err, null);
      return false;
    }
    photo = escapeshell(photo);
    return zbarimg = process.exec("zbarimg " + photo + " -q", function(err, stdout, stderr) {
      if (err != null) {
        callback(err, null);
        return false;
      }
      if (stdout != null) {
        if (stdout.indexOf('QR-Code:') !== -1) {
          stdout = stdout.replace('QR-Code:', '');
          stdout = stdout.slice(0, -2);
          callback(null, stdout);
          return true;
        } else {
          err = new Error('No QR-Code found or barcode not supported');
          callback(err, null);
          return false;
        }
      }
      if (stderr != null) {
        err = new Error(stderr);
        callback(err, null);
        return false;
      }
    });
  };

}).call(this);
